<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ajay Shankar A">
<meta name="dcterms.date" content="2023-11-14">

<title>Ajay Shankar A - CYCLIST BIKE SHARE</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Ajay Shankar A</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">Ajay Shankar A</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ajay333a" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ajay-shankar-a-4b0b121a1/" rel="" target=""><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/ajay333a" rel="" target=""><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">CYCLIST BIKE SHARE</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Analysis</div>
                <div class="quarto-category">Code</div>
                <div class="quarto-category">EDA</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ajay Shankar A </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">November 14, 2023</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#cyclist-bike-share" id="toc-cyclist-bike-share" class="nav-link active" data-scroll-target="#cyclist-bike-share">CYCLIST BIKE SHARE</a>
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#loading-and-formatting-data" id="toc-loading-and-formatting-data" class="nav-link" data-scroll-target="#loading-and-formatting-data">Loading and Formatting Data</a></li>
  <li><a href="#cleaning-the-data" id="toc-cleaning-the-data" class="nav-link" data-scroll-target="#cleaning-the-data">Cleaning the data</a></li>
  </ul></li>
  <li><a href="#analysis-of-data" id="toc-analysis-of-data" class="nav-link" data-scroll-target="#analysis-of-data">Analysis of Data</a>
  <ul class="collapse">
  <li><a href="#aggregating-data-by-rider-type-and-bike-type." id="toc-aggregating-data-by-rider-type-and-bike-type." class="nav-link" data-scroll-target="#aggregating-data-by-rider-type-and-bike-type.">Aggregating data by Rider type and Bike type.</a></li>
  <li><a href="#analysing-data-by-time-of-the-year-and-ride-length" id="toc-analysing-data-by-time-of-the-year-and-ride-length" class="nav-link" data-scroll-target="#analysing-data-by-time-of-the-year-and-ride-length">Analysing data by Time of the year and Ride Length</a></li>
  <li><a href="#analysing-of-stations-and-routes." id="toc-analysing-of-stations-and-routes." class="nav-link" data-scroll-target="#analysing-of-stations-and-routes.">Analysing of Stations and Routes.</a></li>
  <li><a href="#looking-at-filtered-data" id="toc-looking-at-filtered-data" class="nav-link" data-scroll-target="#looking-at-filtered-data">Looking at Filtered data</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="cyclist_bike_202207_202306.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="cyclist-bike-share" class="level1">
<h1>CYCLIST BIKE SHARE</h1>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The analysis is done on <strong>Cyclist Trip Data</strong> obtained from <em>Coursera Google Data Analytics</em> course as part of Cap Stone Project.</p>
<p>The data contains month wise travel usage of bikes from the year of 2015-2023. We will be concentrating on data gathered in between <em>July-2022</em> to <em>June-2023</em> which will cover an entire year.</p>
<p>Let’s load the required packages first</p>
<ul>
<li>Loading <code>tidyverse</code> and <code>gt</code> packages</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="loading-and-formatting-data" class="level3">
<h3 class="anchored" data-anchor-id="loading-and-formatting-data">Loading and Formatting Data</h3>
<ul>
<li>Let’s look at the structure of the data in one of the downloaded <code>.csv</code> files.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>trpdata_july_2022<span class="ot">&lt;-</span><span class="fu">read_csv</span>(<span class="st">"F:/Data_Sci/Cap_Stone_Project/Cyclist_trip_data/202207-divvy-tripdata/202207-divvy-tripdata.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 823488 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): ride_id, rideable_type, start_station_name, start_station_id, end_...
dbl  (4): start_lat, start_lng, end_lat, end_lng
dttm (2): started_at, ended_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(trpdata_july_2022)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 823,488
Columns: 13
$ ride_id            &lt;chr&gt; "954144C2F67B1932", "292E027607D218B6", "5776585258…
$ rideable_type      &lt;chr&gt; "classic_bike", "classic_bike", "classic_bike", "cl…
$ started_at         &lt;dttm&gt; 2022-07-05 08:12:47, 2022-07-26 12:53:38, 2022-07-…
$ ended_at           &lt;dttm&gt; 2022-07-05 08:24:32, 2022-07-26 12:55:31, 2022-07-…
$ start_station_name &lt;chr&gt; "Ashland Ave &amp; Blackhawk St", "Buckingham Fountain …
$ start_station_id   &lt;chr&gt; "13224", "15541", "15541", "15541", "TA1307000117",…
$ end_station_name   &lt;chr&gt; "Kingsbury St &amp; Kinzie St", "Michigan Ave &amp; 8th St"…
$ end_station_id     &lt;chr&gt; "KA1503000043", "623", "623", "TA1307000164", "TA13…
$ start_lat          &lt;dbl&gt; 41.90707, 41.86962, 41.86962, 41.86962, 41.89147, 4…
$ start_lng          &lt;dbl&gt; -87.66725, -87.62398, -87.62398, -87.62398, -87.626…
$ end_lat            &lt;dbl&gt; 41.88918, 41.87277, 41.87277, 41.79526, 41.93625, 4…
$ end_lng            &lt;dbl&gt; -87.63851, -87.62398, -87.62398, -87.59647, -87.652…
$ member_casual      &lt;chr&gt; "member", "casual", "casual", "casual", "member", "…</code></pre>
</div>
</div>
<ul>
<li>Let’s look at the columns and try to understand what they represent
<ul>
<li><code>ride_id</code> is the unique identification token generated for each ride that was initiated.</li>
<li><code>rideable_type</code> indicates the type of bike used for the ride.</li>
<li><code>started_at</code> and <code>ended_at</code> give us the time when the ride began and the ride ended respectively.</li>
<li><code>start_station_name</code> and <code>end_station_name</code> give us the names of stations where ride began and ended respectively.</li>
<li><code>start_station_id</code> and <code>end_station_id</code> are unique ID’s given to stations.</li>
<li><code>start_lat</code> and <code>start_lng</code> represent co-ordinates where the ride began.</li>
<li><code>end_lat</code> and <code>end_lng</code> represent co-ordinates where the ride stopped.</li>
<li><code>member_casual</code> identifies if the rider is a member or casual rider of the bike.</li>
</ul></li>
</ul>
<p>The <code>trpdata_july_2022</code> contains 823488 rows and 13 columns. In the results we can see all the columns and their data types.</p>
<ul>
<li><strong>Lets load data of remaining 11 months.</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>trpdata_aug_2022 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"F:/Data_Sci/Cap_Stone_Project/Cyclist_trip_data/202208-divvy-tripdata/202208-divvy-tripdata.csv"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>trpdata_sept_2022<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"F:/Data_Sci/Cap_Stone_Project/Cyclist_trip_data/202209-divvy-tripdata/202209-divvy-publictripdata.csv"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>trpdata_oct_2022<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"F:/Data_Sci/Cap_Stone_Project/Cyclist_trip_data/202210-divvy-tripdata/202210-divvy-tripdata_raw.csv"</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>trpdata_nov_2022<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"F:/Data_Sci/Cap_Stone_Project/Cyclist_trip_data/202211-divvy-tripdata/202211-divvy-tripdata.csv"</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>trpdata_dec_2022 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"F:/Data_Sci/Cap_Stone_Project/Cyclist_trip_data/202212-divvy-tripdata/202212-divvy-tripdata.csv"</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>trpdata_jan_2023 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"F:/Data_Sci/Cap_Stone_Project/Cyclist_trip_data/202301-divvy-tripdata/202301-divvy-tripdata.csv"</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>trpdata_feb_2023 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"F:/Data_Sci/Cap_Stone_Project/Cyclist_trip_data/202302-divvy-tripdata/202302-divvy-tripdata.csv"</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>trpdata_mar_2023 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"F:/Data_Sci/Cap_Stone_Project/Cyclist_trip_data/202303-divvy-tripdata/202303-divvy-tripdata.csv"</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>trpdata_apr_2023 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"F:/Data_Sci/Cap_Stone_Project/Cyclist_trip_data/202304-divvy-tripdata/202304-divvy-tripdata.csv"</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>trpdata_may_2023 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"F:/Data_Sci/Cap_Stone_Project/Cyclist_trip_data/202305-divvy-tripdata/202305-divvy-tripdata.csv"</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>trpdata_june_2023 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"F:/Data_Sci/Cap_Stone_Project/Cyclist_trip_data/202306-divvy-tripdata/202306-divvy-tripdata.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As structure of <code>.csv</code>’s is same across the all the files lets combine all the <code>.csv</code> files into a single data frame which contains data of all 12 months.</p>
<ul>
<li><strong>Combining all the monthly data to one previous year data(<code>data_one_year_raw</code>).</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>data_one_year_raw <span class="ot">&lt;-</span> <span class="fu">rbind</span>(trpdata_july_2022, trpdata_aug_2022,</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>                     trpdata_sept_2022, trpdata_oct_2022,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                     trpdata_nov_2022, trpdata_dec_2022,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                     trpdata_jan_2023, trpdata_feb_2023,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>                     trpdata_mar_2023, trpdata_apr_2023,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                     trpdata_may_2023, trpdata_june_2023)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_one_year_raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 5,779,444
Columns: 13
$ ride_id            &lt;chr&gt; "954144C2F67B1932", "292E027607D218B6", "5776585258…
$ rideable_type      &lt;chr&gt; "classic_bike", "classic_bike", "classic_bike", "cl…
$ started_at         &lt;dttm&gt; 2022-07-05 08:12:47, 2022-07-26 12:53:38, 2022-07-…
$ ended_at           &lt;dttm&gt; 2022-07-05 08:24:32, 2022-07-26 12:55:31, 2022-07-…
$ start_station_name &lt;chr&gt; "Ashland Ave &amp; Blackhawk St", "Buckingham Fountain …
$ start_station_id   &lt;chr&gt; "13224", "15541", "15541", "15541", "TA1307000117",…
$ end_station_name   &lt;chr&gt; "Kingsbury St &amp; Kinzie St", "Michigan Ave &amp; 8th St"…
$ end_station_id     &lt;chr&gt; "KA1503000043", "623", "623", "TA1307000164", "TA13…
$ start_lat          &lt;dbl&gt; 41.90707, 41.86962, 41.86962, 41.86962, 41.89147, 4…
$ start_lng          &lt;dbl&gt; -87.66725, -87.62398, -87.62398, -87.62398, -87.626…
$ end_lat            &lt;dbl&gt; 41.88918, 41.87277, 41.87277, 41.79526, 41.93625, 4…
$ end_lng            &lt;dbl&gt; -87.63851, -87.62398, -87.62398, -87.59647, -87.652…
$ member_casual      &lt;chr&gt; "member", "casual", "casual", "casual", "member", "…</code></pre>
</div>
</div>
<ul>
<li><code>data_one_year_raw</code> data frame contains data from the month of July-2022 to June-2023.</li>
</ul>
</section>
<section id="cleaning-the-data" class="level3">
<h3 class="anchored" data-anchor-id="cleaning-the-data">Cleaning the data</h3>
<ul>
<li>Checking and counting “NA” in each column of the data frame. Data is much better without “NA” as they can cause problems while aggregating data and calculating averages and sums. We can use <code>map</code> function to perform a function to all of the columns.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>na_in_cols <span class="ot">&lt;-</span> data_one_year_raw <span class="sc">%&gt;%</span> <span class="fu">map</span>(is.na) <span class="sc">%&gt;%</span> <span class="fu">map</span>(sum) <span class="sc">%&gt;%</span> <span class="fu">unlist</span>()</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>na_in_cols</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           ride_id      rideable_type         started_at           ended_at 
                 0                  0                  0                  0 
start_station_name   start_station_id   end_station_name     end_station_id 
            857860             857992             915655             915796 
         start_lat          start_lng            end_lat            end_lng 
                 0                  0               5795               5795 
     member_casual 
                 0 </code></pre>
</div>
</div>
<ul>
<li><p>As NA’s are not present in the times columns i.e, <code>started_at</code> and <code>ended_at</code> we don’t need to worry ourselves about writing <code>na.rm</code> during aggregation and manipulation of data but it is a good practice to do so.</p></li>
<li><p>Finding the length or duration of the rides by making a new column <code>ride_length</code> in minutes and making sure that the <code>ride_length</code> is not negative by using <code>if_else</code> function. Eliminating stations where station names and longitude and latitude co-ordinates are not present.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># As we remove all the NA's it is better to save the data as "data_one_year".</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>data_one_year <span class="ot">&lt;-</span> data_one_year_raw <span class="sc">%&gt;%</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ride_length =</span> <span class="fu">difftime</span>(ended_at, started_at,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                                <span class="at">units =</span> <span class="st">"min"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ride_length =</span> <span class="fu">as.numeric</span>(ride_length))</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>data_one_year <span class="ot">&lt;-</span> data_one_year <span class="sc">%&gt;%</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ride_length =</span> <span class="fu">if_else</span>(ride_length <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="dv">0</span>, ride_length)) <span class="sc">%&gt;%</span> </span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ride_length <span class="sc">&gt;=</span> <span class="dv">2</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>         start_station_name <span class="sc">!=</span> <span class="st">""</span> <span class="sc">&amp;</span> end_station_name <span class="sc">!=</span> <span class="st">""</span> <span class="sc">&amp;</span> </span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(start_lat) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(start_lng) <span class="sc">&amp;</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">is.na</span>(end_lat) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(end_lng)) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(ride_length) <span class="sc">%&gt;%</span> </span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ride_id, rideable_type, ride_length,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>         started_at, ended_at, member_casual)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_one_year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,243,652
Columns: 6
$ ride_id       &lt;chr&gt; "898EAA520DDCF78F", "50BACAD085808776", "961FDB38764FE54…
$ rideable_type &lt;chr&gt; "classic_bike", "classic_bike", "classic_bike", "classic…
$ ride_length   &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,…
$ started_at    &lt;dttm&gt; 2022-07-27 17:51:57, 2022-07-31 20:02:35, 2022-07-06 18…
$ ended_at      &lt;dttm&gt; 2022-07-27 17:53:57, 2022-07-31 20:04:35, 2022-07-06 18…
$ member_casual &lt;chr&gt; "member", "member", "casual", "member", "casual", "membe…</code></pre>
</div>
</div>
</section>
</section>
<section id="analysis-of-data" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-data">Analysis of Data</h2>
<section id="aggregating-data-by-rider-type-and-bike-type." class="level3">
<h3 class="anchored" data-anchor-id="aggregating-data-by-rider-type-and-bike-type.">Aggregating data by Rider type and Bike type.</h3>
<ul>
<li>Aggregating data to see <strong>“Average minutes per ride”</strong> grouped by “bike type” and “rider type” after removing rides less than 2 minutes (As rides less than 2 minutes tend to have the same start and stop stations).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>data_one_year_aggregate <span class="ot">&lt;-</span> data_one_year <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ride_id, rideable_type, member_casual, started_at, ended_at,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>         ride_length, <span class="fu">everything</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ride_length <span class="sc">&gt;=</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="st">"Number of Rides"</span> <span class="ot">=</span> <span class="fu">n</span>(),</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Ride Length"</span> <span class="ot">=</span> <span class="fu">sum</span>(ride_length, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Max Ride Length"</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">max</span>(ride_length), <span class="dv">2</span>),</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Avg Ride Length in Minutes"</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">mean</span>(ride_length), <span class="dv">2</span>),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">.by =</span> <span class="fu">c</span>(member_casual, rideable_type)) <span class="sc">%&gt;%</span> </span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="st">"Avg Ride Length in Minutes"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gt</span>() <span class="sc">%&gt;%</span> <span class="fu">tab_header</span>(<span class="at">title =</span> <span class="st">"Average length of Rides"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_label</span>(<span class="at">member_casual =</span> <span class="st">"Rider type"</span>,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">rideable_type =</span> <span class="st">"Bike type"</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>data_one_year_aggregate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="tbl-avg_ride_legnth" class="anchored">

<div id="qzltoncmqs" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#qzltoncmqs table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#qzltoncmqs thead, #qzltoncmqs tbody, #qzltoncmqs tfoot, #qzltoncmqs tr, #qzltoncmqs td, #qzltoncmqs th {
  border-style: none;
}

#qzltoncmqs p {
  margin: 0;
  padding: 0;
}

#qzltoncmqs .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#qzltoncmqs .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#qzltoncmqs .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#qzltoncmqs .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#qzltoncmqs .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qzltoncmqs .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qzltoncmqs .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#qzltoncmqs .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#qzltoncmqs .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#qzltoncmqs .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#qzltoncmqs .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#qzltoncmqs .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#qzltoncmqs .gt_spanner_row {
  border-bottom-style: hidden;
}

#qzltoncmqs .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#qzltoncmqs .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#qzltoncmqs .gt_from_md > :first-child {
  margin-top: 0;
}

#qzltoncmqs .gt_from_md > :last-child {
  margin-bottom: 0;
}

#qzltoncmqs .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#qzltoncmqs .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#qzltoncmqs .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#qzltoncmqs .gt_row_group_first td {
  border-top-width: 2px;
}

#qzltoncmqs .gt_row_group_first th {
  border-top-width: 2px;
}

#qzltoncmqs .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qzltoncmqs .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#qzltoncmqs .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#qzltoncmqs .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qzltoncmqs .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#qzltoncmqs .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#qzltoncmqs .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#qzltoncmqs .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#qzltoncmqs .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#qzltoncmqs .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qzltoncmqs .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#qzltoncmqs .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#qzltoncmqs .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#qzltoncmqs .gt_left {
  text-align: left;
}

#qzltoncmqs .gt_center {
  text-align: center;
}

#qzltoncmqs .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#qzltoncmqs .gt_font_normal {
  font-weight: normal;
}

#qzltoncmqs .gt_font_bold {
  font-weight: bold;
}

#qzltoncmqs .gt_font_italic {
  font-style: italic;
}

#qzltoncmqs .gt_super {
  font-size: 65%;
}

#qzltoncmqs .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#qzltoncmqs .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#qzltoncmqs .gt_indent_1 {
  text-indent: 5px;
}

#qzltoncmqs .gt_indent_2 {
  text-indent: 10px;
}

#qzltoncmqs .gt_indent_3 {
  text-indent: 15px;
}

#qzltoncmqs .gt_indent_4 {
  text-indent: 20px;
}

#qzltoncmqs .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false"><caption>Table&nbsp;1:  <p>Average minutes per ride</p> </caption>
  <thead>
    <tr class="gt_heading">
      <td colspan="6" class="gt_heading gt_title gt_font_normal gt_bottom_border" style="">Average length of Rides</td>
    </tr>
    
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Rider type">Rider type</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="Bike type">Bike type</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Number of Rides">Number of Rides</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Ride Length">Ride Length</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Max Ride Length">Max Ride Length</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="Avg Ride Length in Minutes">Avg Ride Length in Minutes</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td headers="member_casual" class="gt_row gt_left">member</td>
<td headers="rideable_type" class="gt_row gt_left">classic_bike</td>
<td headers="Number of Rides" class="gt_row gt_right">1630991</td>
<td headers="Ride Length" class="gt_row gt_right">21996488</td>
<td headers="Max Ride Length" class="gt_row gt_right">1497.87</td>
<td headers="Avg Ride Length in Minutes" class="gt_row gt_right">13.49</td></tr>
    <tr><td headers="member_casual" class="gt_row gt_left">casual</td>
<td headers="rideable_type" class="gt_row gt_left">classic_bike</td>
<td headers="Number of Rides" class="gt_row gt_right">781530</td>
<td headers="Ride Length" class="gt_row gt_right">19383358</td>
<td headers="Max Ride Length" class="gt_row gt_right">1497.75</td>
<td headers="Avg Ride Length in Minutes" class="gt_row gt_right">24.80</td></tr>
    <tr><td headers="member_casual" class="gt_row gt_left">casual</td>
<td headers="rideable_type" class="gt_row gt_left">electric_bike</td>
<td headers="Number of Rides" class="gt_row gt_right">709649</td>
<td headers="Ride Length" class="gt_row gt_right">11372659</td>
<td headers="Max Ride Length" class="gt_row gt_right">479.98</td>
<td headers="Avg Ride Length in Minutes" class="gt_row gt_right">16.03</td></tr>
    <tr><td headers="member_casual" class="gt_row gt_left">member</td>
<td headers="rideable_type" class="gt_row gt_left">electric_bike</td>
<td headers="Number of Rides" class="gt_row gt_right">984688</td>
<td headers="Ride Length" class="gt_row gt_right">10968684</td>
<td headers="Max Ride Length" class="gt_row gt_right">480.00</td>
<td headers="Avg Ride Length in Minutes" class="gt_row gt_right">11.14</td></tr>
    <tr><td headers="member_casual" class="gt_row gt_left">casual</td>
<td headers="rideable_type" class="gt_row gt_left">docked_bike</td>
<td headers="Number of Rides" class="gt_row gt_right">136794</td>
<td headers="Ride Length" class="gt_row gt_right">6899998</td>
<td headers="Max Ride Length" class="gt_row gt_right">32035.45</td>
<td headers="Avg Ride Length in Minutes" class="gt_row gt_right">50.44</td></tr>
  </tbody>
  
  
</table>
</div>
</div>
</div>
</div>
<p>We can clearly notice in <a href="#tbl-avg_ride_legnth">Table&nbsp;1</a> that <strong>member</strong> riders have more number of rides with both <strong>classic and electric bikes</strong> while the average ride length is higher with <strong>casual</strong> riders.</p>
<ul>
<li>Calculating and visualizing <strong>Average ride length</strong> by “Rider type”.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>average_ride_by_rideable_type <span class="ot">&lt;-</span> data_one_year <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">"Rider type"</span> <span class="ot">=</span> member_casual, <span class="st">"Bike type"</span> <span class="ot">=</span> rideable_type) <span class="sc">%&gt;%</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">ride_length =</span> <span class="fu">sum</span>(ride_length, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">ride_count =</span> <span class="fu">n</span>(),</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_ride_length =</span> ride_length<span class="sc">/</span>ride_count,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">.by =</span> <span class="fu">c</span>(<span class="st">`</span><span class="at">Rider type</span><span class="st">`</span>, <span class="st">`</span><span class="at">Bike type</span><span class="st">`</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="st">`</span><span class="at">Rider type</span><span class="st">`</span>, avg_ride_length)) <span class="sc">+</span> </span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">fill =</span> <span class="st">`</span><span class="at">Bike type</span><span class="st">`</span>), <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span> </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Bike type"</span>, <span class="at">y =</span> <span class="st">"Avg Length of Ride(Minutes)"</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">title  =</span> <span class="st">"Average ride length by Bike type"</span>) <span class="sc">+</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">18</span>),</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>average_ride_by_rideable_type</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-avg_ride_length" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="cyclist_bike_202207_202306_files/figure-html/fig-avg_ride_length-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;1: Average Ride Length by Rider type and Member type</figcaption>
</figure>
</div>
</div>
</div>
<p>The above <a href="#fig-avg_ride_length">Figure&nbsp;1</a> clearly shows that members average ride lengths between bike types doesn’t differ much for <strong>member</strong> riders but differs with <strong>casual</strong> riders upto <strong>8 minutes</strong>.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Further down in the analysis “docked_bike” type is dropped as no proper documentation is available in the course.</p>
</div>
</div>
</section>
<section id="analysing-data-by-time-of-the-year-and-ride-length" class="level3">
<h3 class="anchored" data-anchor-id="analysing-data-by-time-of-the-year-and-ride-length">Analysing data by Time of the year and Ride Length</h3>
<section id="ride-patterns-across-the-weeks-and-months-of-the-year" class="level4">
<h4 class="anchored" data-anchor-id="ride-patterns-across-the-weeks-and-months-of-the-year">Ride Patterns Across the Weeks and Months of the Year</h4>
<ul>
<li>Calculating and visualizing ride patterns in a week for number of rides.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>rideable_order <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"classic_bike"</span>, <span class="st">"electric_bike"</span>, <span class="st">"docked_bike"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>rides_on_days <span class="ot">&lt;-</span> data_one_year <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(rideable_type <span class="sc">!=</span> <span class="st">"docked_bike"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">month =</span> <span class="fu">month</span>(started_at, <span class="at">label =</span> <span class="cn">TRUE</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">abbr =</span> <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rideable_type =</span> <span class="fu">factor</span>(rideable_type,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>                                <span class="at">levels =</span> rideable_order)) <span class="sc">%&gt;%</span>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">wday</span>(started_at, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>))) <span class="sc">+</span> </span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> member_casual), <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>month, <span class="at">nrow =</span> <span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Day of the Week"</span>, <span class="at">y =</span> <span class="st">"Number of rides"</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Riding pattrens on Weekdays of each Month"</span>,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"From July-2022 to June-2023"</span>,</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Type of Rider"</span>) <span class="sc">+</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">18</span>))</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>rides_on_days </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Ride_patterns_in_weekdays" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="cyclist_bike_202207_202306_files/figure-html/fig-Ride_patterns_in_weekdays-1.png" class="img-fluid figure-img" width="1050"></p>
<figcaption class="figure-caption">Figure&nbsp;2: Riding pattrens in Weekdays of each Month</figcaption>
</figure>
</div>
</div>
</div>
<p>The above <a href="#fig-Ride_patterns_in_weekdays">Figure&nbsp;2</a> clearly shows how the number of rides change due to seasons. In winters the number of rides decrease very drastically may be because of temperature and snow. In Summers the number of rides are at its peak.</p>
<p>The number of rides driven by <strong>member</strong> riders are increases through the week especially in working week days but for casual riders the rides increase in the weekends. The <a href="#fig-Ride_patterns_in_weekdays">Figure&nbsp;2</a> shows number of rides on Saturdays and Sundays by casual members overtake membership riders in the months of July and August.</p>
</section>
<section id="comparing-variation-in-ride-lengths-of-average-and-total-ride-lengths-by-bike-type." class="level4">
<h4 class="anchored" data-anchor-id="comparing-variation-in-ride-lengths-of-average-and-total-ride-lengths-by-bike-type.">Comparing variation in ride lengths of average and total ride lengths by bike type.</h4>
<p>Aggregating data for the visualization.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>rides_on_days <span class="ot">&lt;-</span> data_one_year <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">day =</span> <span class="fu">wday</span>(started_at, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">month =</span> <span class="fu">month</span>(started_at, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">ride_count =</span> <span class="fu">n</span>(),</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">sum_ride_length =</span> <span class="fu">sum</span>(ride_length, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_ride_length =</span> <span class="fu">mean</span>(ride_length, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">.by =</span> <span class="fu">c</span>(month, day, member_casual))</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>rides_on_days </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 168 × 6
   month day       member_casual ride_count sum_ride_length avg_ride_length
   &lt;ord&gt; &lt;ord&gt;     &lt;chr&gt;              &lt;int&gt;           &lt;dbl&gt;           &lt;dbl&gt;
 1 July  Wednesday member             45928         603429.            13.1
 2 July  Sunday    member             44328         685475.            15.5
 3 July  Wednesday casual             31631         703360.            22.2
 4 July  Saturday  member             51852         816009.            15.7
 5 July  Thursday  casual             34895         759013.            21.8
 6 July  Friday    member             46398         614466.            13.2
 7 July  Friday    casual             41198         959168.            23.3
 8 July  Monday    casual             32960         917333.            27.8
 9 July  Monday    member             38746         530041.            13.7
10 July  Sunday    casual             59528        1714086.            28.8
# ℹ 158 more rows</code></pre>
</div>
</div>
<p><strong>Let’s visualize the aggregated data</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>rides_on_days_len <span class="ot">&lt;-</span> rides_on_days <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(day, sum_ride_length))<span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">fill =</span> member_casual), <span class="at">position =</span> <span class="st">"dodge"</span>)<span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>month, <span class="at">ncol =</span> <span class="dv">3</span>)<span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Day of the Week"</span>, <span class="at">y =</span> <span class="st">"Total Length of Rides (Minutes)"</span>,</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Total Minutes driven by Riders"</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Type of Rider"</span>) <span class="sc">+</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>,</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">18</span>))</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>rides_on_days_len</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Riding_patterns_by_total_ride_length" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="cyclist_bike_202207_202306_files/figure-html/fig-Riding_patterns_by_total_ride_length-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Total Ride lengths through out the year by member types.</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>rides_on_days_len_avg <span class="ot">&lt;-</span> rides_on_days <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(day, avg_ride_length))<span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">fill =</span> member_casual), <span class="at">position =</span> <span class="st">"dodge"</span>)<span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>month, <span class="at">ncol =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Day of the Week"</span>, <span class="at">y =</span> <span class="st">"Average Length of Rides (Minutes)"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">"Average Minutes driven by Riders"</span>,</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Type of Rider"</span>) <span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>,</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">18</span>))</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>rides_on_days_len_avg</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-Riding_patterns_by_avg_ride_length" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="cyclist_bike_202207_202306_files/figure-html/fig-Riding_patterns_by_avg_ride_length-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;4: Average Ride lengths through out year by member types.</figcaption>
</figure>
</div>
</div>
</div>
<p>The <strong>ride length</strong> is varying across months and seasons just as number of rides but <strong>average ride length</strong> is not fluctuating that much across the year.</p>
</section>
<section id="rides-through-out-the-day" class="level4">
<h4 class="anchored" data-anchor-id="rides-through-out-the-day">Rides through out the day</h4>
<p>Let’s look at when the rides are starting to know at what time of day the rides peak and are at the lowest.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>rides_on_time_of_day <span class="ot">&lt;-</span> data_one_year <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">time_of_day =</span> <span class="fu">format</span>(<span class="fu">as.POSIXct</span>(ended_at), <span class="st">"%H"</span>),</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">wk_day =</span> <span class="fu">wday</span>(started_at, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">FALSE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">ride_id =</span> <span class="fu">n</span>(),</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.by =</span> <span class="fu">c</span>(time_of_day, member_casual))</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>rides_on_time_of_day <span class="sc">%&gt;%</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(time_of_day, ride_id, <span class="at">fill =</span> ride_id )) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Hour of the day"</span>, <span class="at">y =</span> <span class="st">"Number of Rides"</span>,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Max Rides"</span>) <span class="sc">+</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>member_casual, <span class="at">ncol =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">number_format</span>(<span class="at">scale =</span> <span class="fl">1e-3</span>, <span class="at">suffix =</span> <span class="st">"K"</span>)) <span class="sc">+</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="cyclist_bike_202207_202306_files/figure-html/rides through time of the day-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li>Most of the rides start at 5:00 PM in the evening showing <strong>most of the rides begin after office hours</strong> for both <code>caual</code> and <code>member</code> riders but members peak twice at 8:00 AM and 5:00 PM but the casual riders peak only once at 5:00 PM.</li>
</ul>
</section>
</section>
<section id="analysing-of-stations-and-routes." class="level3">
<h3 class="anchored" data-anchor-id="analysing-of-stations-and-routes.">Analysing of Stations and Routes.</h3>
<ul>
<li>Removing “NA” and blanks from the stations columns.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>data_one_year <span class="ot">&lt;-</span> data_one_year_raw <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ride_length =</span> <span class="fu">difftime</span>(ended_at, started_at,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">units =</span> <span class="st">"min"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ride_length =</span> <span class="fu">as.numeric</span>(ride_length)) <span class="sc">%&gt;%</span> </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ride_length =</span> <span class="fu">if_else</span>(ride_length <span class="sc">&lt;</span> <span class="dv">0</span>, <span class="dv">0</span>, ride_length)) <span class="sc">%&gt;%</span> </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ride_length <span class="sc">&gt;=</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(start_station_name, end_station_name ) <span class="sc">%&gt;%</span> </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(start_station_name <span class="sc">!=</span> <span class="st">""</span> <span class="sc">&amp;</span> end_station_name <span class="sc">!=</span> <span class="st">""</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>         started_at <span class="sc">!=</span> ended_at)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_one_year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,243,662
Columns: 14
$ ride_id            &lt;chr&gt; "954144C2F67B1932", "57765852588AD6E0", "B5B6BE4431…
$ rideable_type      &lt;chr&gt; "classic_bike", "classic_bike", "classic_bike", "cl…
$ started_at         &lt;dttm&gt; 2022-07-05 08:12:47, 2022-07-03 13:58:49, 2022-07-…
$ ended_at           &lt;dttm&gt; 2022-07-05 08:24:32, 2022-07-03 14:06:32, 2022-07-…
$ start_station_name &lt;chr&gt; "Ashland Ave &amp; Blackhawk St", "Buckingham Fountain …
$ start_station_id   &lt;chr&gt; "13224", "15541", "15541", "TA1307000117", "15535",…
$ end_station_name   &lt;chr&gt; "Kingsbury St &amp; Kinzie St", "Michigan Ave &amp; 8th St"…
$ end_station_id     &lt;chr&gt; "KA1503000043", "623", "TA1307000164", "TA130700005…
$ start_lat          &lt;dbl&gt; 41.90707, 41.86962, 41.86962, 41.89147, 41.88461, 4…
$ start_lng          &lt;dbl&gt; -87.66725, -87.62398, -87.62398, -87.62676, -87.644…
$ end_lat            &lt;dbl&gt; 41.88918, 41.87277, 41.79526, 41.93625, 41.86712, 4…
$ end_lng            &lt;dbl&gt; -87.63851, -87.62398, -87.59647, -87.65266, -87.641…
$ member_casual      &lt;chr&gt; "member", "casual", "casual", "member", "member", "…
$ ride_length        &lt;dbl&gt; 11.750000, 7.716667, 58.483333, 26.300000, 8.716667…</code></pre>
</div>
</div>
<ul>
<li>Making a new column to identify travelled routes.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>data_one_year <span class="ot">&lt;-</span> data_one_year <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">stations_travelled =</span> <span class="fu">paste</span>(start_station_name, </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"-"</span>, end_station_name))</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_one_year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 4,243,662
Columns: 15
$ ride_id            &lt;chr&gt; "954144C2F67B1932", "57765852588AD6E0", "B5B6BE4431…
$ rideable_type      &lt;chr&gt; "classic_bike", "classic_bike", "classic_bike", "cl…
$ started_at         &lt;dttm&gt; 2022-07-05 08:12:47, 2022-07-03 13:58:49, 2022-07-…
$ ended_at           &lt;dttm&gt; 2022-07-05 08:24:32, 2022-07-03 14:06:32, 2022-07-…
$ start_station_name &lt;chr&gt; "Ashland Ave &amp; Blackhawk St", "Buckingham Fountain …
$ start_station_id   &lt;chr&gt; "13224", "15541", "15541", "TA1307000117", "15535",…
$ end_station_name   &lt;chr&gt; "Kingsbury St &amp; Kinzie St", "Michigan Ave &amp; 8th St"…
$ end_station_id     &lt;chr&gt; "KA1503000043", "623", "TA1307000164", "TA130700005…
$ start_lat          &lt;dbl&gt; 41.90707, 41.86962, 41.86962, 41.89147, 41.88461, 4…
$ start_lng          &lt;dbl&gt; -87.66725, -87.62398, -87.62398, -87.62676, -87.644…
$ end_lat            &lt;dbl&gt; 41.88918, 41.87277, 41.79526, 41.93625, 41.86712, 4…
$ end_lng            &lt;dbl&gt; -87.63851, -87.62398, -87.59647, -87.65266, -87.641…
$ member_casual      &lt;chr&gt; "member", "casual", "casual", "member", "member", "…
$ ride_length        &lt;dbl&gt; 11.750000, 7.716667, 58.483333, 26.300000, 8.716667…
$ stations_travelled &lt;chr&gt; "Ashland Ave &amp; Blackhawk St - Kingsbury St &amp; Kinzie…</code></pre>
</div>
</div>
<ul>
<li>Finding which route is most traveled by <strong>casual riders</strong>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>most_travelled_routes_casual <span class="ot">&lt;-</span> data_one_year <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(member_casual <span class="sc">==</span> <span class="st">"casual"</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>         ride_length <span class="sc">&gt;=</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">ride_count =</span> <span class="fu">n</span>(),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_ride_length =</span> <span class="fu">round</span>(<span class="fu">mean</span>(ride_length), <span class="dv">2</span>),</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">.by =</span> <span class="fu">c</span>(stations_travelled)) <span class="sc">%&gt;%</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(ride_count))</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(most_travelled_routes_casual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 3
  stations_travelled                                  ride_count avg_ride_length
  &lt;chr&gt;                                                    &lt;int&gt;           &lt;dbl&gt;
1 Streeter Dr &amp; Grand Ave - Streeter Dr &amp; Grand Ave         8259            46.3
2 DuSable Lake Shore Dr &amp; Monroe St - DuSable Lake S…       5726            38.3
3 DuSable Lake Shore Dr &amp; Monroe St - Streeter Dr &amp; …       4840            27.1
4 Michigan Ave &amp; Oak St - Michigan Ave &amp; Oak St             3754            50.9
5 Millennium Park - Millennium Park                         3188            45.4
6 Streeter Dr &amp; Grand Ave - DuSable Lake Shore Dr &amp; …       2663            27.8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">NROW</span>(most_travelled_routes_casual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 130373</code></pre>
</div>
</div>
<p><strong>Streeter Dr &amp; Grand Ave - Streeter Dr &amp; Grand Ave</strong> stands to be the most popular station with <strong>9698 rides</strong> by <strong>casual</strong> riders.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>most_travelled_routes_member <span class="ot">&lt;-</span> data_one_year  <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(member_casual <span class="sc">==</span> <span class="st">"member"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">ride_count =</span> <span class="fu">n</span>(),</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">total_ride_length =</span> <span class="fu">sum</span>(ride_length),</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">ride_length =</span> <span class="fu">round</span>(<span class="fu">mean</span>(ride_length), <span class="dv">2</span>),</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">.by =</span> stations_travelled) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(ride_count))</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(most_travelled_routes_member)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  stations_travelled                    ride_count total_ride_length ride_length
  &lt;chr&gt;                                      &lt;int&gt;             &lt;dbl&gt;       &lt;dbl&gt;
1 Ellis Ave &amp; 60th St - University Ave…       6149            25928.        4.22
2 University Ave &amp; 57th St - Ellis Ave…       5771            26605.        4.61
3 Ellis Ave &amp; 60th St - Ellis Ave &amp; 55…       5676            28427.        5.01
4 Ellis Ave &amp; 55th St - Ellis Ave &amp; 60…       5347            27187.        5.08
5 State St &amp; 33rd St - Calumet Ave &amp; 3…       4037            17795.        4.41
6 Calumet Ave &amp; 33rd St - State St &amp; 3…       3836            15538.        4.05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">NROW</span>(most_travelled_routes_member)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 144802</code></pre>
</div>
</div>
<p><strong>Ellis Ave &amp; 60th St - University Ave &amp; 57th St</strong> stands as the most traveled route by <strong>member</strong> riders with <strong>6153</strong> rides per anum.</p>
<ul>
<li>Finding which station has most ride starting points and which station has most ending points.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>most_starting_points <span class="ot">&lt;-</span> data_one_year <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">ride_count =</span> <span class="fu">n</span>(),</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">.by =</span> start_station_name) <span class="sc">%&gt;%</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(start_station_name, ride_count) <span class="sc">%&gt;%</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(ride_count, <span class="at">n =</span> <span class="dv">10</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>most_starting_points</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   start_station_name                 ride_count
   &lt;chr&gt;                                   &lt;int&gt;
 1 Streeter Dr &amp; Grand Ave                 63899
 2 DuSable Lake Shore Dr &amp; Monroe St       36757
 3 Michigan Ave &amp; Oak St                   35050
 4 DuSable Lake Shore Dr &amp; North Blvd      34167
 5 Wells St &amp; Concord Ln                   32175
 6 Clark St &amp; Elm St                       31832
 7 Kingsbury St &amp; Kinzie St                30820
 8 Millennium Park                         29894
 9 Theater on the Lake                     28864
10 Wells St &amp; Elm St                       27152</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>most_starting_points<span class="sc">$</span>ride_count <span class="sc">%&gt;%</span> <span class="fu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 350610</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>most_ending_points <span class="ot">&lt;-</span> data_one_year <span class="sc">%&gt;%</span> </span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">ride_count =</span> <span class="fu">n</span>(),</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">.by =</span> end_station_name) <span class="sc">%&gt;%</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(end_station_name, ride_count)  <span class="sc">%&gt;%</span> </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(ride_count, <span class="at">n =</span> <span class="dv">10</span>)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>most_ending_points</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   end_station_name                   ride_count
   &lt;chr&gt;                                   &lt;int&gt;
 1 Streeter Dr &amp; Grand Ave                 65542
 2 DuSable Lake Shore Dr &amp; North Blvd      37093
 3 Michigan Ave &amp; Oak St                   35977
 4 DuSable Lake Shore Dr &amp; Monroe St       35629
 5 Wells St &amp; Concord Ln                   32879
 6 Clark St &amp; Elm St                       31394
 7 Millennium Park                         31023
 8 Kingsbury St &amp; Kinzie St                29805
 9 Theater on the Lake                     29482
10 Wells St &amp; Elm St                       27360</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>most_ending_points<span class="sc">$</span>ride_count <span class="sc">%&gt;%</span> <span class="fu">sum</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 356184</code></pre>
</div>
</div>
<p><strong>Streeter Dr &amp; Grand Ave</strong> found to be the most popular station as most rides start and end at that station.</p>
</section>
<section id="looking-at-filtered-data" class="level3">
<h3 class="anchored" data-anchor-id="looking-at-filtered-data">Looking at Filtered data</h3>
<p>Just because we filtered the data with NA’s that does not mean that the data is not helpful, it just means that it does not our fulfill specific need when calculating or manipulating data.</p>
<p>Let’s look at NA’s in the data once again.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>na_in_cols <span class="ot">&lt;-</span> data_one_year_raw <span class="sc">%&gt;%</span> <span class="fu">map</span>( <span class="sc">~</span><span class="fu">sum</span>(<span class="fu">is.na</span>(.))) <span class="sc">%&gt;%</span> <span class="fu">unlist</span>()</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>na_in_cols</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           ride_id      rideable_type         started_at           ended_at 
                 0                  0                  0                  0 
start_station_name   start_station_id   end_station_name     end_station_id 
            857860             857992             915655             915796 
         start_lat          start_lng            end_lat            end_lng 
                 0                  0               5795               5795 
     member_casual 
                 0 </code></pre>
</div>
</div>
<ul>
<li>We can see that the <code>start_station_name</code> and <code>end_station_name</code> have majority of NA’s it means that rides are starting and ending where stations are not there.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>prop_na <span class="ot">&lt;-</span> na_in_cols[<span class="st">"start_station_name"</span>]<span class="sc">/</span><span class="fu">nrow</span>(data_one_year_raw)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>prop_na</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>start_station_name 
          0.148433 </code></pre>
</div>
</div>
<ul>
<li>14.84% of data in <code>start_station_name</code> is missing and good thing is that none of the <code>start_lng</code> and <code>start_lat</code> have any NA’s and we can use this for find the most traveled routes.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>data_na_one_year <span class="ot">&lt;-</span> data_one_year_raw <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">is.na</span>(start_station_name) <span class="sc">|</span> start_station_name <span class="sc">==</span> <span class="st">""</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(end_lat, end_lng)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_na_one_year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 857,860
Columns: 13
$ ride_id            &lt;chr&gt; "DCB3D2C9B63999EC", "D1ACA8280DA02AE3", "EF98673429…
$ rideable_type      &lt;chr&gt; "electric_bike", "electric_bike", "electric_bike", …
$ started_at         &lt;dttm&gt; 2022-07-04 15:04:26, 2022-07-12 14:43:51, 2022-07-…
$ ended_at           &lt;dttm&gt; 2022-07-04 15:32:38, 2022-07-12 14:49:28, 2022-07-…
$ start_station_name &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ start_station_id   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ end_station_name   &lt;chr&gt; "Ashland Ave &amp; Blackhawk St", "Cornell Ave &amp; Hyde P…
$ end_station_id     &lt;chr&gt; "13224", "KA1503000007", "KA1503000007", "847", "48…
$ start_lat          &lt;dbl&gt; 41.95, 41.80, 41.80, 41.74, 42.02, 41.95, 41.95, 41…
$ start_lng          &lt;dbl&gt; -87.64, -87.59, -87.59, -87.55, -87.69, -87.67, -87…
$ end_lat            &lt;dbl&gt; 41.90707, 41.80241, 41.80241, 41.73000, 42.01000, 4…
$ end_lng            &lt;dbl&gt; -87.66725, -87.58692, -87.58692, -87.55000, -87.690…
$ member_casual      &lt;chr&gt; "member", "member", "member", "member", "member", "…</code></pre>
</div>
</div>
<ul>
<li>Now let’s make new columns <code>start_point</code> with <code>start_lng</code> and <code>start_lat</code> and <code>end_point</code> with <code>end_lat</code> and <code>end_lng</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>data_na_one_year <span class="ot">&lt;-</span> data_na_one_year <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">start_point =</span> <span class="fu">paste</span>(start_lat, start_lng),</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">end_point =</span> <span class="fu">paste</span>(end_lat, end_lng))</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_na_one_year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 857,860
Columns: 15
$ ride_id            &lt;chr&gt; "DCB3D2C9B63999EC", "D1ACA8280DA02AE3", "EF98673429…
$ rideable_type      &lt;chr&gt; "electric_bike", "electric_bike", "electric_bike", …
$ started_at         &lt;dttm&gt; 2022-07-04 15:04:26, 2022-07-12 14:43:51, 2022-07-…
$ ended_at           &lt;dttm&gt; 2022-07-04 15:32:38, 2022-07-12 14:49:28, 2022-07-…
$ start_station_name &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ start_station_id   &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ end_station_name   &lt;chr&gt; "Ashland Ave &amp; Blackhawk St", "Cornell Ave &amp; Hyde P…
$ end_station_id     &lt;chr&gt; "13224", "KA1503000007", "KA1503000007", "847", "48…
$ start_lat          &lt;dbl&gt; 41.95, 41.80, 41.80, 41.74, 42.02, 41.95, 41.95, 41…
$ start_lng          &lt;dbl&gt; -87.64, -87.59, -87.59, -87.55, -87.69, -87.67, -87…
$ end_lat            &lt;dbl&gt; 41.90707, 41.80241, 41.80241, 41.73000, 42.01000, 4…
$ end_lng            &lt;dbl&gt; -87.66725, -87.58692, -87.58692, -87.55000, -87.690…
$ member_casual      &lt;chr&gt; "member", "member", "member", "member", "member", "…
$ start_point        &lt;chr&gt; "41.95 -87.64", "41.8 -87.59", "41.8 -87.59", "41.7…
$ end_point          &lt;chr&gt; "41.907066 -87.667252", "41.802406 -87.586924", "41…</code></pre>
</div>
</div>
<ul>
<li>Aggregating data to check for the most traveled routes without a <code>start_station</code> name.</li>
</ul>
<p>First join <code>start_point</code> and <code>end_point</code> to make <code>route_travelled</code> then count the rides by <code>routes_travelled</code> to see the most traveled path.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>most_travelled_na_routes <span class="ot">&lt;-</span> data_na_one_year <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(start_point <span class="sc">!=</span> end_point) <span class="sc">%&gt;%</span> </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">route_travelled =</span> <span class="fu">paste</span>(start_point, <span class="st">","</span>, end_point)) <span class="sc">%&gt;%</span> </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">ride_count =</span> <span class="fu">n</span>(),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">.by =</span> route_travelled) <span class="sc">%&gt;%</span></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(ride_count, <span class="at">n=</span><span class="dv">10</span>)</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>most_travelled_na_routes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 2
   route_travelled                             ride_count
   &lt;chr&gt;                                            &lt;int&gt;
 1 41.79 -87.6 , 41.8 -87.59                         1459
 2 41.79 -87.59 , 41.79 -87.6                        1354
 3 41.8 -87.59 , 41.79 -87.6                         1335
 4 41.79 -87.6 , 41.79 -87.59                        1320
 5 41.8 -87.6 , 41.79 -87.6                          1099
 6 41.79 -87.6 , 41.78509714636 -87.6010727606       1058
 7 41.79 -87.6 , 41.8 -87.6                           999
 8 41.79 -87.6 , 41.799568 -87.594747                 917
 9 41.79 -87.6 , 41.78 -87.6                          697
10 41.89 -87.63 , 41.9 -87.63                         690</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(most_travelled_na_routes[<span class="st">"ride_count"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10928</code></pre>
</div>
</div>
<ul>
<li><strong>10928</strong> rides are not small when compared to most traveled routes, but 10928 rides in 5 million rides is not that high.</li>
</ul>
</section>
<section id="conclusions" class="level3">
<h3 class="anchored" data-anchor-id="conclusions">Conclusions</h3>
<ul>
<li><p>As casual members go for long rides on the weekends, offers on weekend rides with membership buying may help attract more memberships and might also make membership riders to make weekend end trips.</p></li>
<li><p>To increase the memberships of the <strong>Cyclist Bike Share</strong> the company needs to place stations where most new rides are coming up and routes are travelled more.</p></li>
</ul>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>